### ISSUE TITLE
DOTENV_CONFIG_PATH

### ISSUE THREAD

**Issue by sebastienbages** [madeindjs/rest-api.ts#3]
Salut @madeindjs !

J'ai une erreur que je n'arrive pas à résoudre au chapitre 3 dans l'exécution du premier test.
J'ai créé le script `"test": "DOTENV_CONFIG_PATH=.test.env ts-mocha -r reflect-metadata -r dotenv/config src/**/*.spec.ts"` dans le fichier `package.json` mais j'obtiens l'erreur suivante :
``
DOTENV_CONFIG_PATH' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
``

J'ai essayé tout un tas de choses grâce à la doc de `dotenv` mais en vain...

Merci par avance pour ton aide.

P.S: mon repo est à jour si tu veux essayer 😉 (https://github.com/sebastienbages/API-Bannis)

**Comment by madeindjs** [comment]
Salut @sebastienbages ,

Cette erreur survient car tu utilise Windows directement. Or la syntaxe que tu utilise est Bash qui est utilisé sur UNIX (Aka Linux et Mac).

Il y a plusieurs solutions comme utiliser WSL ou sinon utiliser la librairie [cross-env](https://www.npmjs.com/package/cross-env). Voici une [réponse sur Stackoverflow](https://stackoverflow.com/a/66994680/5935198) à ce sujet.

N'hésite pas à revenir vers moi si tu rencontre des difficultés.

**Comment by sebastienbages** [comment]
Merci pour ta réponse @madeindjs 👍.
Effectivement je développe sous Windows.
J'ai déjà entendu parler de WSL et je me demande si cela n'est pas un peu lourd pour une simple commande.
Est-ce une utilisation courante dans ce genre de cas ? Que me conseil-tu ?
Je suis curieux de savoir ce que tu ferais dans ce genre de cas.
Merci beaucoup 🙏.

**Comment by madeindjs** [comment]
Si tu cherches juste a apprendre et à faire un petit projet tu peux rester avec la lib cross-env. Je te conseille quand même de faire un switch vers WSL.

Si tu es vraiment motivé, je te conseille de te dirriger directement vers Docker qui est vraiment un super outil et qui te servira sûrement dans ta carrière de dev ;)

**Comment by sebastienbages** [comment]
Je suis motivé donc je vais me diriger vers Docker 😀.
Cela me servira j'en suis persuadé 😋.
Je te tiens au courant, merci pour ton retour 👍
